const LIST_PRODUCTS = 'products/LIST_PRODUCTS';
const CLEAR_PRODUCTS = 'products/CLEAR_PRODUCTS';

const LIST_PRODUCTS_STATUS = 'products/LIST_PRODUCTS_STATUS';
const CLEAR_PRODUCTS_STATUS = 'products/CLEAR_PRODUCTS_STATUS';

export default {
  LIST_PRODUCTS,
  CLEAR_PRODUCTS,
  LIST_PRODUCTS_STATUS,
  CLEAR_PRODUCTS_STATUS,
};
