const LIST_PRODUCTS = 'products/LIST_PRODUCTS';
const CLEAR_PRODUCTS = 'products/CLEAR_PRODUCTS';
const CREATE_PRODUCT = 'products/CREATE_PRODUCT';
const REMOVE_PRODUCT = 'products/REMOVE_PRODUCT';
const FIND_PRODUCT = 'products/FIND_PRODUCT';
const EDIT_PRODUCT = 'products/EDIT_PRODUCT';

const LIST_PRODUCTS_STATUS = 'products/LIST_PRODUCTS_STATUS';
const CLEAR_PRODUCTS_STATUS = 'products/CLEAR_PRODUCTS_STATUS';
const EDIT_PRODUCT_STATUS = 'products/EDIT_PRODUCT_STATUS';

const SELECT_PRODUCTS = 'products/SELECT_PRODUCTS';
const CLEAR_SELECTED_PRODUCTS = 'products/CLEAR_SELECTED_PRODUCTS';

const EXPORT_PRODUCTS = 'products/EXPORT_PRODUCTS';

export default {
  LIST_PRODUCTS,
  CLEAR_PRODUCTS,
  EDIT_PRODUCT,
  LIST_PRODUCTS_STATUS,
  CLEAR_PRODUCTS_STATUS,
  CREATE_PRODUCT,
  EDIT_PRODUCT_STATUS,
  REMOVE_PRODUCT,
  FIND_PRODUCT,

  SELECT_PRODUCTS,
  CLEAR_SELECTED_PRODUCTS,

  EXPORT_PRODUCTS,
};
