---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: it4-front
  namespace: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: it4-front
    spec:
      containers:
      - name: it4-front
        image: acr360.azurecr.io/it4-front:0.0.12
        ports:
        - name: http
          containerPort: 80
      imagePullSecrets:
      - name: acr-auth
---
kind: Service
apiVersion: v1
metadata:
  name: it4-front
  namespace: core
spec:
  selector:
    app: it4-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
  type: NodePort