const LIST_CHANNELS = 'channels/LIST_CHANNELS';
const CLEAR_CHANNELS = 'channels/CLEAR_CHANNELS';

const LIST_CHANNELS_STATUS = 'channels/LIST_CHANNELS_STATUS';
const CLEAR_CHANNELS_STATUS = 'channels/CLEAR_CHANNELS_STATUS';

const LIST_ALL_BRANDS_PER_CHANNEL_ID =
  'channels/LIST_ALL_BRANDS_PER_CHANNEL_ID';

const LIST_CHANNEL_BRANDS = 'channels/LIST_CHANNEL_BRANDS';
const CLEAR_CHANNEL_BRANDS = 'channels/CLEAR_CHANNEL_BRANDS';

const LIST_CHANNEL_CATEGORIES = 'channels/LIST_CHANNEL_CATEGORIES';
const CLEAR_CHANNEL_CATEGORIES = 'channels/CLEAR_CHANNEL_CATEGORIES';

export default {
  LIST_CHANNELS,
  CLEAR_CHANNELS,

  LIST_CHANNELS_STATUS,
  CLEAR_CHANNELS_STATUS,

  LIST_ALL_BRANDS_PER_CHANNEL_ID,

  LIST_CHANNEL_BRANDS,
  LIST_CHANNEL_CATEGORIES,

  CLEAR_CHANNEL_BRANDS,
  CLEAR_CHANNEL_CATEGORIES,
};
