const LIST_CHANNELS = 'channels/LIST_CHANNELS';
const CLEAR_CHANNELS = 'channels/CLEAR_CHANNELS';

const LIST_CHANNELS_STATUS = 'channels/LIST_CHANNELS_STATUS';
const CLEAR_CHANNELS_STATUS = 'channels/CLEAR_CHANNELS_STATUS';

export default {
  LIST_CHANNELS,
  CLEAR_CHANNELS,

  LIST_CHANNELS_STATUS,
  CLEAR_CHANNELS_STATUS,
};
