const HANDLE_LOGIN = 'user/HANDLE_LOGIN';
const HANDLE_LOGOUT = 'user/HANDLE_LOGOUT';
const VERIFY_TOKEN = 'user/VERIFY_TOKEN';
const FORGOT_PASSORD = 'user/FORGOT_PASSORD';

export default {
  HANDLE_LOGIN,
  HANDLE_LOGOUT,
  VERIFY_TOKEN,
  FORGOT_PASSORD,
};
