const UPDATE_PASSWORD = 'loggedUser/UPDATE_PASSWORD';
const CHANGE_USER_PASSWORD_LOGGED_IN =
  'loggedUser/CHANGE_USER_PASSWORD_LOGGED_IN';

export default {
  UPDATE_PASSWORD,
  CHANGE_USER_PASSWORD_LOGGED_IN,
};
