const LIST_ORDERS = 'orders/LIST_ORDERS';
const FIND_ORDER = 'orders/FIND_ORDER';
const LIST_ORDER_STATUS = 'orders/LIST_ORDER_STATUS';
const INVOICE_ORDER = 'orders/INVOICE';
const CANCEL_ORDER = 'orders/CANCEL_ORDER';
const CANCEL_ORDER_ITEMS = 'orders/CANCEL_ORDER_ITEMS';

export default {
  LIST_ORDERS,
  FIND_ORDER,

  LIST_ORDER_STATUS,
  INVOICE_ORDER,
  CANCEL_ORDER,
  CANCEL_ORDER_ITEMS,
};
