const LIST_ORDERS = 'orders/LIST_ORDERS';
const FIND_ORDER = 'orders/FIND_ORDER';
const LIST_ORDER_STATUS = 'orders/LIST_ORDER_STATUS';
const INVOICE_ORDER_PRODUCTS_SKUS = 'orders/INVOICE_PRODUCTS_SKUS';

export default {
  LIST_ORDERS,
  FIND_ORDER,

  LIST_ORDER_STATUS,
  INVOICE_ORDER_PRODUCTS_SKUS,
};
