const LIST_CHANNEL_PRODUCTS = 'channelProducts/LIST_CHANNEL_PRODUCTS';
const FIND_CHANNEL_PRODUCT = 'channelProducts/FIND_PRODUCT';
const REMOVE_CHANNEL_PRODUCT = 'channelProducts/REMOVE_CHANNEL_PRODUCT';
const LIST_CHANNEL_PRODUCTS_SUMMARY =
  'channelProducts/LIST_CHANNEL_PRODUCTS_SUMMARY';
const ENABLE_OR_DISABLE_CHANNEL_PRODUCT =
  'channelProducts/ENABLE_OR_DISABLE_CHANNEL_PRODUCT';

export default {
  LIST_CHANNEL_PRODUCTS,
  FIND_CHANNEL_PRODUCT,
  REMOVE_CHANNEL_PRODUCT,
  LIST_CHANNEL_PRODUCTS_SUMMARY,
  ENABLE_OR_DISABLE_CHANNEL_PRODUCT,
};
