const LIST_ALL_CATEGORY_ATTRIBUTE_CHANNEL_ID =
  'channelCategories/LIST_ALL_CATEGORY_ATTRIBUTE_CHANNEL_ID';
const CLEAR_ALL_CATEGORY_ATTRIBUTE_CHANNEL_ID =
  'channelCategories/CLEAR_ALL_CATEGORY_ATTRIBUTE_CHANNEL_ID';

export default {
  LIST_ALL_CATEGORY_ATTRIBUTE_CHANNEL_ID,
  CLEAR_ALL_CATEGORY_ATTRIBUTE_CHANNEL_ID,
};
