const HANDLE_MOBILE = 'layout/HANDLE_MOBILE';
const HANDLE_SIDER_COLLAPSED = 'layout/HANDLE_SIDER_COLLAPSED';
const HANDLE_BREAKPOINT_CHANGE = 'layout/HANDLE_BREAKPOINT_CHANGE';

export default {
  HANDLE_MOBILE,
  HANDLE_SIDER_COLLAPSED,
  HANDLE_BREAKPOINT_CHANGE,
};
