const NOTIFICATIONS_RECEIVED = 'notifications/NOTIFICATIONS_RECEIVED';
const CLEAR_ACTIVE_NOTIFICATIONS = 'notifications/CLEAR_ACTIVE_NOTIFICATIONS';
const LIST_NOTIFICATIONS = 'notifications/LIST_NOTIFICATIONS';
const CLEAR_NOTIFICATIONS = 'notifications/CLEAR_NOTIFICATIONS';
const VIEW_NOTIFICATION = 'notifications/VIEW_NOTIFICATION';

const REMOVE_NOTIFICATION = 'notifications/REMOVE_NOTIFICATION';

export default {
  NOTIFICATIONS_RECEIVED,
  CLEAR_ACTIVE_NOTIFICATIONS,
  LIST_NOTIFICATIONS,
  CLEAR_NOTIFICATIONS,
  VIEW_NOTIFICATION,

  REMOVE_NOTIFICATION,
};
